apiVersion: v1
kind: Secret
metadata:
    name: ryot-secrets
    namespace: health
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:wdfD2AzA1l89Tc+3706w6HVd0r88n3T80cIosw5TwXd95R0pm3EcCccbHpg55V4BZO5Wo3EJTkt9YqrbkfS2+2BhheYQfgcZ72YDDEreegTpMdygYWzZ6VQenCg+iKmLDWIhp6/QQ5WZTz1xeVKCjg==,iv:weQWtM0WAGAd8/GTXSpuTUBtsydPmtG8aD3e85QEzE4=,tag:fWspAoPVET/GoHhOClAKbQ==,type:str]
    SERVER_ADMIN_ACCESS_TOKEN: ENC[AES256_GCM,data:Kj2jB7+5yOVrUiyJr+qsUY0pGw==,iv:S/ndCrZ5bQt5hw47B1z4fZSETvW8xDVo8TJ644bsQjU=,tag:ylpQX1RC0IWkhXt6ltDpNA==,type:str]
    SERVER_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:jrsPgjfgPyaj0cUqP+gfd3DkOOJkY7yMIULkZxfBm5cQvvwvHz5ofs937HTFLrpf,iv:os4169LEdxcoHwCG4/2LSnMYPB6DSHkMXrmB2Kgz30w=,tag:E84WRoPCfOpr2zVhaW1bNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMTRvTFJGWW10dGZSUGNk
            SnpkOEJNeXd4SlQ1L2pBOTRhbExka1RKblFFCmtocUhwZHV1anRIeXhpSUNHWi9z
            cWxlYWR4Zjd5MDNhVWlFM1FGY0pMZ2sKLS0tIGV4UHcrM2NhYTVwVm5kU3RiZXRq
            U0Fjbm9OQ1RXT1F1MmREZ1FGK3pMTDQKQ4pXhlB8TeoV9lUW9iQQgzxGqUUCGDcV
            5xfgbJw/YCKIe7y6qVaRX1AIFBoZN+d936+pjmunPfNegoW/bFgxJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:48:07Z"
    mac: ENC[AES256_GCM,data:L557e961VX6u78ztOhpmIa1BQz2b4RdebMVfz89KrZ4XasEkP1w6qf+YZzEySFDTOSeTJbwiJ9GyCCGEPEpdA4aHKfhxbVRD86g5rNQTY6z7cMkUSVycbMRWdWhVu7rTrhoJTkHdtXUG83KpTGELOE2xYlLeK3ctCVuyTkmgHRc=,iv:vDxQGJF4kN33ug/QQj840wp6AtIL/4n4Dh4/zEuJSmA=,tag:B5bbG0HGmRHHLI+NZAlMlA==,type:str]
    version: 3.13.3
