apiVersion: v1
kind: Secret
metadata:
    name: ryot-secrets
    namespace: health
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:BiX3QrIVETcWUxHthyvAJIHrwYl9eI8HDu1O55W7xb+T4xei/GKcxDSUv+eK+Uei+xQqg4OTdwt8cuVX4ZkMbToOYaL0Av4nBHA77XWeNiyAR6IZxhBaiWhlByxNbr+JtLU=,iv:+28LLVJvJ9V/LGV5Gu2oJ9gFCauzd+HEWYU9aRaMLqE=,tag:Cocn6F9W6qet0xguKhN4jA==,type:str]
    SERVER_ADMIN_ACCESS_TOKEN: ENC[AES256_GCM,data:ijCy8ZGYYiR/XSvsMdkGb+QY/g==,iv:oQSKrPjyWM2ET173L0Tgf9Tg2Zg2M0UsjsMNLZz4neE=,tag:cxVETrlvOi7vF5qjhJm8NQ==,type:str]
    SERVER_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:S1bnrzfy7AoETZmKHAnSIg7jHgvQgvVHK7uxE6jUJdywknHO5sHf05ckrYQfXsEj,iv:vKuTiEpyQ/jBqnpjUvs7mKXyFUhPGMGP5haJj0QuxIc=,tag:aI8SW1i3u+eVVJOvfIJpBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJY2FoQ05iSEg4ZitzcWRI
            bzBaalNHQnJoakhpakNjZDhLTlU2RFRydkZJCnJrcCszdlBaVXFNTTZEL2FMRDg3
            QnhtdHFkcW01Tm1oUWEvV3oyZThkOTAKLS0tIE1xSEZmU2E4ZzV1SDZEd2syVlYz
            UGFQcWFBanIvaWNHRlVuT29peUh3UE0KLsX0ETzwGYbmbzc4W2IdQxqAdm4xAwJD
            SQ2PWlLLqEZ/Y/um8QT+vl1GNsB5DXhRi0KlUQ9vozU01RqO3Yu/7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T19:33:11Z"
    mac: ENC[AES256_GCM,data:R4FRFmJCAbhe3gEhe/7GoVoeE3Cfn7WHXnpODSLMPibGswgE8gRTWhXaEe3pr+3Xldwja1YB4cQh0ws4dJ1H5Py4N0QxZRtiHwZf4YXEg5ZDW6k43d2u5L/RGTJBMAj/52iAjcSTZ/K42/M70UAD3AGy/e7JZvmD8COFLQl7veg=,iv:IORuVxVccAUmH+PNBsqQqSkXjVrEDrD3xUTqa5JUJO0=,tag:I73Zxk2OZigZDKowyUv7Ig==,type:str]
    version: 3.13.3
