# ==============================================================================
# SECTION 1: ANSIBLE CONNECTION DEFAULTS
# ==============================================================================
ansible_user: devops
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3
ansible_remote_tmp: /tmp/.ansible-${USER}/tmp

# ==============================================================================
# SECTION 2: GLOBAL SYSTEM SETTINGS
# ==============================================================================
timezone: "Asia/Kolkata"

# ==============================================================================
# SECTION 3: INFRASTRUCTURE SOURCE OF TRUTH (Terraform Hydration)
# ==============================================================================
gcp_project_id: "homelab-ops-482221"
gcp_region: "asia-south1"
gcp_zone: "asia-south1-a"
project_name: "homelab"
gcp_environment: "prod"
subnet_cidr: "10.0.1.0/24"

# ==============================================================================
# SECTION 4: PROXMOX INFRASTRUCTURE DEFINITIONS
# ==============================================================================
proxmox_api_url: "https://192.168.0.3:8006/api2/json"
proxmox_api_token_id: "root@pam!terraform"
proxmox_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLBRLuIw6ZBC/6xYG/kH/Q90D4Js3DJ396gpIEg4GNX vsc@fedora"

# Gateway Configuration
proxmox_gateway_config:
  ip: "192.168.0.10"
  onboot: false

# VM Specs - The Blueprint for Lab
proxmox_vms:
  # Zone A: Lab (Academy Plane)
  jumpbox:
    vmid: 200
    ip: "192.168.0.20"
    cores: 1
    memory: 1024
    startup_param: "order=4,up=40,down=40"
    onboot: false
  
  server:
    vmid: 210
    ip: "192.168.0.21"
    cores: 2
    memory: 2048
    startup_param: "order=3,up=40,down=40"
    onboot: false
  
  node_0:
    vmid: 220
    ip: "192.168.0.22"
    cores: 2
    memory: 2048
    startup_param: "order=3,up=40,down=40"
    onboot: false
  
  node_1:
    vmid: 221
    ip: "192.168.0.23"
    cores: 2
    memory: 2048
    startup_param: "order=3,up=20,down=20"
    onboot: false

  # Zone M: Management
  ops_center:
    vmid: 900
    ip: "192.168.0.5"
    cores: 2
    memory: 2048
    disk_size: "20G"
    onboot: true

  # Zone P: Production
  k3s_prod:
    vmid: 500
    ip: "192.168.0.30"
    cores: 2
    memory: 8192
    disk_size: "20G"
    onboot: true