apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
  namespace: database
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: local-path
  managed:
    roles:
      - name: n8n
        ensure: present
        login: true
        passwordSecret:
          name: postgres-ha-app-user
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: postgres-ha-app-user
