apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "REPLACE_ME"

  # N8n Security key
  # To Generate a random key run cmd: openssl rand -hex 24
  N8N_ENCRYPTION_KEY: "REPLACE_ME"