apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: productivity
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZnlaYAV8gguduV7em6oV4zk29qH9qQtMAQIYerbzid0fv/VsEEBGWFGc1JBlat4KZDKY/rsyS04CGy8xUSOc3zBai3AnK09Pg3OAwXibVGedEh5G2RM8fVdb9ohxrCi3HE3cznxj,iv:R8PAbVKr7kfmNiRYFiaGPGjHpPBbE+840MNp2kXUmFs=,tag:gjkQHTNv+4cfLs8QHXwvLw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:31iilrn15DhzUPNnNzzMfOKlC9w=,iv:N8KsetDnomxEYmTC7AKReVW3bpEG/9UosYoFBBhISsM=,tag:PGTXMzictMspaZwLPriVVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza1d0TXBseUE2NW5FcS9a
            Q0hkK2V4TzNEbjZ3eVlsaE1xMkVwd0xJT21FCng0UStkTDJoaGhnd1ZKTEFvNU1k
            cVdIZTA2NXc3NG9qWkNUVE92YWZ0clUKLS0tIGNIRTVPMllEMlRlSzN3UHFVTEoz
            dXdDRHZpV2x1Ymk3VmxWZHlQOUhmWVEKd9fDhNpgO15B+QhXg4bDfGulVa3veOvp
            uTyMsN307Z3wWSClWfGcOmljSFiyEfY2GFtTMSqq9Yi1qBMy0dX5Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T19:33:11Z"
    mac: ENC[AES256_GCM,data:BkeKba0cvlt8gnfbxGzyNCR1r6oYyEp6qo3VdhZPsXJihjKHb5wl+ibs+phYMPj39t8zWxUW4ItsUphiDVBFmlctlMuQSGNgFALI4m6WFj6XpQYXvbQ4yINaSdtsEVKc1KE+YQKg6PQNyzxKLCM3X+iHkyg8lZ/rUOs863KVzwY=,iv:XNv1eyvTl//VeMzvJ47F13Cd75s6wDgHa31mdMC/SVg=,tag:MMfvdfkIL0lWrRV3+t+g7Q==,type:str]
    version: 3.13.3
