apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: productivity
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:2upwdkAm61IsbwMTmXqOt/M1MCFk1pQj9cu4nBH7AEOAD4mSVGp4JBkdQ2ntxm90orIQpydQaVKshM+adYfcykVTIR8MD6Y+KpgXe1YomM71/ZkGdF2hPY4hr5jr9Vy0SfJhfQpuyoYIoilycbENI39CtfQ=,iv:DxOUYaPQfKmokT8w9kawzJgUVyHXUhS+aImaMbPUAWQ=,tag:k2DW6vt5TPlfhAfgV6HiBQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:GPl5EHOFQKe4l+ExFOKQVPt0OQ4=,iv:F/RcQRgh/qRb2J4H/YjVnTbovoFKvQHU857X27SO+Rg=,tag:Jvke5piwPZxAfv+4E8gLdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ2k4d3k2ek53VUpNTDhL
            VnVteENUbUswYzVRZEJRQm9tbHdVeWpPN1FNCkpLRmVGeVptL0haTGM5TnF2RE5h
            eGtteGRuMGVNenpFN2EvQkh5bXNJa3MKLS0tIEJabE44Vkl4bGRMV0l4bW1PcnN6
            MzRmOXFaS09SbmFjb2pyQzFpVnI1TEUK0kjfr8chA91yGDI7+/KJqSn6ehoLANzZ
            PveMlRO14gKAyfyIBk/X1wcF10BgDre7uorT576qpaSXwBh1Sj4YEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:47:22Z"
    mac: ENC[AES256_GCM,data:nc7jHwTSC9ZYon0RFQmM5syNsuRKuqovYD9kwQxDnxQ/pa6VmhctWr3GJ/k/nSg3fJEPkc1mtQcoqoqAggSGg+p/jVgw2wrJlAF/byJcr9O5Mm6y37ewORdiHzBFEbtM0h8hZ/QVU+bNxFeArhEVXdI+gxdX7H9xrjgSldXAVp0=,iv:w9CNiiBe51+AYOVdxbhY0hCqtBV57R1dmVpMzcoggWY=,tag:zgC0IUoO2KiyxGazW3fKaA==,type:str]
    version: 3.13.3
