apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: documents
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:TBl4ly0=,iv:6eFpg/tUAAEYDH49hYGiFLU5kvKKc1UyNdM2fLfHvtQ=,tag:bxT+UwfbZmqKbEbGEvXaJA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:bqIBszciKmAiaILp8yZrlm4=,iv:Lh6n5XOWbyQVK7x3jCyL/V4D2jKTgNaKKsCtG0BO4wo=,tag:XjtHecuXiv4lh5dVjvdqpw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:4LxOKtQlRBw5g7IZmqxZ56RXFmh3janq0fNXMeNaWbdi/8J4LMY+w+E=,iv:u5BGogDqZL7sjFHZEWR4yd+9kPpifbm8aDZaVpGlAu8=,tag:Ox+fneUZ0Rex5R8ceZMNLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWnV0VDBvZFZnNG5KbmN0
            NzEwcjFKZkRmZmdGSWM4RzNocWZJY052dTNNCkJ2RWxnVHB4WUZqVDhWdlByOXRO
            VDJ0d0lYcUY4ajdjSEh2UWp3ZHVKMGsKLS0tIEllcTRwYm1pdG5KWkpQaVE4UW5q
            STUrQjVGMlMrVzRhSkhZcnB5bkx0Q0EKbeCuDkSNC0vMUvXzI3ZvanOTD6gFCrwW
            YckDf190HvEqNiHFjlHG2q3cXVwH1PaP41T5oSWJeDMLmMtFKSrHIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:18:45Z"
    mac: ENC[AES256_GCM,data:o4Wu+6VZj18tZnl1c+Oo/bvSeAdRK7xAP2RhIn5V7d16AvBZ7+p5nkDAtQfNfk11nrCAcsluNZDC1xNtZWyCeLN/BL06rm29uPLiEWIbXXjYbUIdJc6WYLe9ZK5L0+Bdq6+WSCecp6KAM0pCSv9VhVMrvxNinDugfB93GfVCy5g=,iv:CFoBvalsZvEJj8MScN9b6IWlaYaIk8+8wg7DzW89a44=,tag:KQnsjIzTCX7w4MLhntuN9g==,type:str]
    version: 3.13.3
