apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: documents
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:+M5PBW8=,iv:gvUECtPZk6M8Qd8B+N2Bs7zn7QZkRd5xlw2ZZLXATP4=,tag:FKxwg2Tn/3lbVSyd2Vvwtw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:f8uC0vx3Luy+iTYIHOujJcU=,iv:QuiZf9trj51ks9VzCQy8s5Y8zPEoQKccWmGcujAzuYo=,tag:lgkCXUXcHDtbZZgeVCTOJw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:1qujqX//YeAmddYlNPkK7TQCFRVCX0dMHNiGUWBaNWByyb5D8B9Rtio=,iv:G/5mpjXwY0KcaGIbFmMAOzBImEEtWQ6suDHKlbeK+7Q=,tag:6K0S6DlEFascYgUA0nsbUg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:AFp1FAA59z+lutToJKh6OM7gxbyuEudAknGZXxo=,iv:U5PNLq458hsJkYYYNXhIm00mATx0WY7MwScd6SEQw4w=,tag:5NRwGqDbQswbmRyPlK8f7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT0ZvSXQ5K2RTVEpkQ2lI
            Tkt5Mk4yanMxTDNWelp0YXJhS05VaUpQeEhBCjRPeTFvRWhqL25SaFB1MEFOODhz
            anl6a0hDcTV5cXVrakxleCtrYUlhQ3cKLS0tIGNpRW04TnBTU29lcW9jRE4wOUhq
            ZmlXRG5nVU9Kd0grTVpIaXNPSXk3YnMK0hX1SKuLTsU4ETsG8crRkiyx/ftDkyfn
            S9P/qQujW075a3wuG4xSyToKvt+uweCHHVDurBu9CgniU3YuqdRByQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:46:43Z"
    mac: ENC[AES256_GCM,data:Qv1ZMG1LIsaFVMog4q33YvQldsz0DHF6frFSzB4w8NCMxGjAHlYxPFgBBIT7Uckjgcb4Bs4z/4v5aksmdDKxk5UGULKGmz4WhGA7XnXqPGJdBibSkFGrDfAOpANUnzztniuMEcHooqQzg369UhNoc249pm52WeqZ3EBSDXGplTw=,iv:IjaMm546NsC+2BoZ6db0f/paRvyw+5k96Ku07maZiAQ=,tag:cpdIP9UYKsUKVOSmKjDvtg==,type:str]
    version: 3.13.3
