apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
  namespace: automation
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: pdf-generator
