apiVersion: v1
kind: Secret
metadata:
    name: kwatch-config
    namespace: kwatch
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:TS355kh+3d4h6ny2tSRRe0ND8XQfz2RXFKgDNADOiYlwtWP7fGohjVaHbVqhfzUNfJFNFU3bFZgemIcxUxVUDb70BLVdG1W1IPNRss2eYA3c7metX4p9qdeFXP5u+eqjIfYI15j9Q6obS6xx5HaF2APhFZr7JOy0R72QqtoBUySowT5aLSv1+I0CF454W8li4xg3H7/Kx6PSBdGiuU9vl90aDvaeQoIZDHDo/P5HC+3+jK/pmg8fobXSqA2nQZEFiRVDkXpFEDDPFP7l0V/OGxlvlUiBbLdBTU2HWlilseDhVnP5gUEA4L5AjTyNum3fereRoSUHMxKv1zjFaiGYEuijd78+mwXSP9776ZQKLQ894ciGCrEPYT+qCBdn+Uyzaw1m/sDKSqXlFVIEweXDtDY1/UexEe0Dw6y1/1CgT0uzG6RNpWrzo4A6hXjF4nZOnlZgFOq9XPF/3JQesLRpAbAlC0F2hfQJLVXsm43GEg1LlJkKFZ/Xx7WGhCw2xjysGslJ86QlZZ3MAwQbpQtTYnS3oH3w3xdJQrGgwZmd5udgiMkS0oXWzmpMPfpkcsXE/4CqOAfrYklGhN1zVHS6wwA0ZYUGgwvj3WjCLIdYYNtPwfuXXA==,iv:sanB3E8z/8WOHi+VgYCMauLkThKaTBDOrrrB9DjUL6k=,tag:9QBKtqNaxZ163KSjg+CVnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUJvNXVwWjhsRnpmTkph
            QWdnQzRCcFdneVQ3bDVhaC9qNTYwY2hYR240CnBYMXp2aExlYWR5N1V6MUVKcG1k
            NExDVURYbk10eGhoVGduZVU4TFVZRmcKLS0tIFJrb3NEekdoYVZOS1FuU1NhL2Nz
            blVOeGVWVkRncFdjV2ttOFdCRWQzVXcK9fppTDt3dtccEp+QDPLEyLKXUAdzDzPm
            bnf5lsoOELhnG46PpMW38huS8p1ZuPUI+c8z5etBMIqCiBbJfH/+Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T20:38:43Z"
    mac: ENC[AES256_GCM,data:MYU3NNAceHnH9ZMnb6SYgEPDhrrbrc1z6hmQ9Dq5q0HmVxF6DrYkJT8fl56LUGpsJ0t0sobb4HgmP1ZD2QeTTcEghdRVcD5ABhlgNt0lcOqnQrxT0q+h0PtT+6Lv/iGJbtIWgFRZb0iAdoobjW5+jNrfuS26o8l68EwMrjQrDe0=,iv:xkJwaUU4r1ud2KyL+1AsGhhQ11zK3fKVYOZ4SbzSkOI=,tag:zDC30FCtebvcdF2cMH6AaQ==,type:str]
    version: 3.13.3
