apiVersion: v1
kind: Secret
metadata:
    name: kwatch-config
    namespace: kwatch
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:wiWvwMvvqJ4rp9oWo9TckcBckscfyo5DmgHXzr8eFd7dxIgqFgMvGyhLmWEFuHQ2N4YUxHUimTsSzM1EpavAGEKCGeoh+6GCfrfQn3EO0vC7XmNaM76rOk2mc/CDdZe+GsUbC6w07qRuBM7dqsS55T7lY7nAmZnm1TuDfD+1BEd6cwvlhWsMvSPR7u2a0Jb2PJrY84s5LCi8NZyN6IrBA63/raG0NeCrPIOJcaA61/UtP8iVkD3YVRpBiX57ivrkmmL/sQVUkdUr0C28iH5V0SGG71pOXl7XNLw+Q8H2DDRldeK37fjR9DmLjzqtS/9g/o7FAs9LoFrNGG8zNR6mL6p2vcg3D/e0RBq61VIwVR56iCy9OfTzAVRaureGb0xa+0FIBH7wYJlrgEe6T7qNqJjb7tCtQoKMA70wvmo69mGTT+Axl6HZHB1S/rpb7HGVcre00ivygN5m3S2U9wHuXB/NH/rMk6VVRgDcuBEds1m07cNnK21Ju4Akaudbtgc7gj3EedpnPB55PPrAGflatAY+o8XFthq1fyvcAAp25prW6tNPZVq04cpD9DOmUv/ox7XeiSSvuWd8s3VNMoUjPBq0NtxGXwst3idV/WvrTKfTOpf+0P1xG0ANm3xVqEx5YT5mK73VRK84gByOjJhne9nPU6NlA8JpHeI=,iv:4rHxmXfq+cqZckZ3ELT8IfXqcmaGsqt0nxAAxo25Ilg=,tag:nlvPYF44kk2iyl8MbcFUPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RnV1Z00yQ1Zyamx6S3hD
            VDJlZi9NcWxhc1Y4QVlMSi9TSWd4VHdlYjNZCmdINDVXeWlHbmpkLzVMQWtPRTNI
            cENhNTNSdFZ6TGx2djBzbDlvSWRTZEkKLS0tIDBjc0N1OU93RndWZTZvTWszU01k
            TGJtUFlxelBwelBaOCtMd285eWt1bUkKo/pcgWDelhfalW4vvtNNTGJagIvW16ym
            w1W2X7pBNHjfn4TcSMdTxXEjlr7na75cI9jwlWRx8wWI82hBxecLqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T20:53:03Z"
    mac: ENC[AES256_GCM,data:odeUDWAGtkteb7+QLzI26Dbyxe8uisGByqAdg0oCYMUSdAPOumYGHsQaINQE+/GCaB3dJjvX/EFCjvqGtx8zmq0yI6+gLXdot8dytmX9ENz3Ah54y53v7knY83JWexq3HiYtyfd9pSo8w8D3Pho784EeZGxWJ5KDWp6FSBRZ3L8=,iv:+63GtKq7R29YpSwowE4m9/92rZF/xUOoCmIe1OJZzbY=,tag:LHkIsvzLhaCkReHw2tRcqQ==,type:str]
    version: 3.13.3
