apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflared/cloudflared.yaml
  - homepage/homepage.yaml
  - monitoring/grafana-telemetry-ingress.yaml
  - docs/docs.yaml
  - postgres-operator
