apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflared/cloudflared.yaml
  - homepage
  - monitoring/grafana-telemetry-ingress.yaml
  - docs
  - postgres-operator
  - kwatch
