apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:9bdOM52ftWeMJ9sgAQkFSUOSAu0vDw==,iv:GJOooKs4qPANxhxSDxw6yVo52q/ulbWQsTjO2aGlNt4=,tag:U/gsmPwjm2nHhQaJgdG3Uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VHRUVFhyaDBvQlRwTUt2
            Q2VSUVpXeFlIcnVIQTl0T21aODJFQVpWM0c4Cm1pZEtTUFJHY3p1TWZ3RGhPSTc1
            L1FlNFlXdDdzSW53WXBrRlB5TW5UVWcKLS0tIFduVUg1anZZVTlFQTJ3M3p1UWpv
            cEcvdlJwdm40cW5Kc2xXN2pTbzZTNVUKRqWBQt0z2PoLZPa6OYeOXkVBPFfKdzKm
            oVQytvkB1mdvifHQbzxcptd4G1vjQ0Yo/Lfjcf3wHD3AWwfSsyIFyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T05:20:19Z"
    mac: ENC[AES256_GCM,data:kcmJ3h3HFftG4REmaWMR/5EKZgjEJk/8pwLFmWkaS7sbVtY0oWIehsJO/efbK1cQuUIQx+aNqc4tdKmpM/d1ttUt9yik17e6tG8kQZwG27tn/u1tkOhZ39Dr1+4iIA6mlcqEff7Bqjnf0ygWbemYB8SsePD5DNaTWW3H2eKoeho=,iv:JcZwv6QK/Xrfnyi+/ybm+ybcKBieL7vCkHgOUksAFHw=,tag:HJ3kBK3CIFgFGABUc7nghQ==,type:str]
    version: 3.13.3
