apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: automation
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:iQz74UH9oYcjB38SaqHtzQmaDfar7zSUB/7EUnG5RTxc1g2PiB99mHNO1Vg7wqv8,iv:URh8s+EL0FQeOdchbRJToHLm1iIz8CPLGhiQ09Zmp/Y=,tag:4okbQe+4wxUGvmt2D4j2zw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:IjrD,iv:oe/JDw3DhpBAvJ/uREq7TX0qkCn38gs9/ulrYjsZCVY=,tag:bOWRS8qEEAeOAhcrCBfDCA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K5ttcK7o94zGds6Gc+xGaNnqoNLQu1KaMh6E8Fo=,iv:TuodUbud33MJQkI3fIh+TtXWxB4ofunvbW2+/2h1DjI=,tag:UExRohUJBvWIJex9JVshzw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:IXJt,iv:Tb2ykp3YjzGjtQDjJVqzzK3LPuVTsiKnWGKzrHMklAw=,tag:SulBjzqkrZNseDgKu0kN6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRmQzTTI1UzhZVTRVVVdo
            bFZJZmJHeGgySkdETFNKRjJDN2RsMENuQVJzCkN6Nm9iZzY3VHdZQWwxMFdwM0lN
            ekJkSTNMNGNaSy93bkhDK2sxWm91ZVUKLS0tIFgzZTZhbnZ3eUJHa05CWEx1OTNK
            YWJzbW56d1JkZVBwMWdYeFFqSFdtSUUKtEC/FbSarq2KZwnNczGTaFkaxZXJqEQr
            CPrnYDRQFqGwu2fI3XTi8mEMfGAPm8uOmfKq9/8faRk4mXQyCyo0rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngq6yxpu6lszk4735vap6twle8jgp982f2g7hcq8rhhudhfz6cksyjv9y9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:08:55Z"
    mac: ENC[AES256_GCM,data:DSKI+51SvytQ8BusaO3iqPb4lf2wOmJ8EcKMDOspuofONLE7XDqn35ldTVbQWQWYncgcGxG9SZNlkbHK1w1rTdtqexpOZtB0AmSD2b0DGwU6oGgAd14zS0Lc3RYJqT6zNLs0hOCKuozVRiGOQAZ8E3Oboc2/EJeXLbeHubVA1pU=,iv:mUMFzVKVE2ABLd54eCLPqF8G0ZiGbX2BzrUs7FqRfPA=,tag:oUSdbkKpmFIqxsE1lFX9Vg==,type:str]
    version: 3.13.3
