# yaml-language-server: $schema=https://json.schemastore.org/any.json
- greeting:
    text_size: 2xl
    text: "Vijay Kumar Singh | Sovereign Cloud"

- greeting:
    text_size: sm
    text: "Production Bare-Metal Kubernetes Platform • Hybrid Cloud Automation & Fleet Operations"

- search:
    provider: duckduckgo
    target: _blank

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showNodes: true
    nodes:
      show: true
      cpu: true
      memory: true
