all:
  children:
    # -----------------------------------
    # INFRASTRUCTURE (The Hypervisor)
    # -----------------------------------
    hypervisor:
      hosts:
        pve:
          ansible_host: 192.168.0.3
          ansible_user: root
    
    # -----------------------------------
    # ZONE MGMT
    # -----------------------------------
    management:
      hosts:
        ops-center:
          ansible_host: ops-center

    # -----------------------------------
    # ZONE PROD
    # -----------------------------------
    production:
      hosts:
        k3s-prod:
          ansible_host: 192.168.0.30

    # -----------------------------------
    # ZONE LAB (K8s The Hard Way)
    # -----------------------------------
    lab:
      children:
        load_balancers:
          hosts:
            gateway:
              ansible_host: 192.168.0.10
        k8s_cluster:
          hosts:
            server:
              ansible_host: 192.168.0.21
            node-0:
              ansible_host: 192.168.0.22
            node-1:
              ansible_host: 192.168.0.23